### ISSUE TITLE
Error 502 after update

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#110]
mattermost log : 
```
[2018/05/10 22:01:33 CEST] [INFO] Le serveur écoute sur le port [::]:8065
[2018/05/10 22:01:33 CEST] [EROR] Unable to setup forwarding: listen tcp :80: bind: permission denied
[2018/05/10 22:01:33 CEST] [CRIT] Erreur de démarrage du serveur, err : accept tcp [::]:8065: use of closed network connection
[2018/05/10 22:01:33 CEST] [INFO] API version 3 is scheduled for deprecation. Please see https://api.mattermost.com for details.
[2018/05/10 22:01:33 CEST] [INFO] Lancement de 4 concentrateurs websocket
[2018/05/10 22:01:33 CEST] [INFO] Starting workers
[2018/05/10 22:01:33 CEST] [INFO] Starting schedulers.
```

nginx log : 
```
2018/05/11 13:31:47 [error] 2757#0: *7931 connect() failed (111: Connection refused) while connecting to upstream, client: 194.2.202.93, server: mat.krashboyz.org, request: "POST /api/v4/use
rs/status/ids HTTP/1.1", upstream: "http://127.0.0.1:8065/api/v4/users/status/ids", host: "mat.krashboyz.org"
```
yunohost -v  (on a VPS)
```
yunohost: 
  repo: stable
  version: 2.7.12
yunohost-admin: 
  repo: stable
  version: 2.7.12
moulinette: 
  repo: stable
  version: 2.7.12
ssowat: 
  repo: stable
  version: 2.7.12
```

**Comment by isAAAc** [comment]
service mattermost status
```
● mattermost.service - Mattermost
   Loaded: loaded (/etc/systemd/system/mattermost.service; enabled)
   Active: active (running) since jeu. 2018-05-10 22:01:33 CEST; 15h ago
 Main PID: 2925 (platform)
   CGroup: /system.slice/mattermost.service
           ├─2925 /var/www/mattermost/bin/platform
           └─2946 plugins/jira/plugin.exe
```

**Comment by isAAAc** [comment]
do you need more information to help me to repair this nginx error 111 ?
i don't understand what could change since the update, cause it was working perfectly before

**Comment by kemenaran** [comment]
(Sorry for the delay, I’m currently traveling)


Mmm, it seems that Mattermost is configured with the `Forward80To443` option set to true. When the server starts, in addition of binding to the local port, it also tries to bind to the port 80 (to redirect it to the port 443 for SSL) – but fails, because only root processes can bind to privileged ports (and the Matermost server doesn’t run as root).

The fix should be to:

1. Stop the server with `sudo service mattermost stop`
2. Edit the `/var/www/mattermost/config/config.json` manually, and to set the `Forward80To443` option to false.
3. Restart the server with `sudo service mattermost start`

Does it fix the error?

**Comment by isAAAc** [comment]
> Does it fix the error ?

Yes ! perfect ;) you're the king of mattermost_ynh <3 

Thx a lot for your help ;)

**Comment by kemenaran** [comment]
You're welcome ;)
