### ISSUE TITLE
Add a Rasbberry-compatible package

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/mattermost_ynh#124]
can u please make the apps compatible with a raspberry
1960 WARNING Mattermost requires an x86_64 machine, but this one is 'armv7l'.
thanks to u for now i have this wen i try to install

thanks for u

**Comment by kemenaran** [comment]
It would be neat to support Raspberry Pi instead.

The problem is that Mattermost doesn't officially supports arm architectures. Building it manually for arm [should work](https://github.com/mattermost/mattermost-server/issues/7054), but the Raspberry lacks enough RAM to build it directly on the machine. It would need to be cross-compiled on an external machine, and downloaded from there.

This seems a little too much unsupported and complicated – but if someone wants to make a PR for this, I'm open to contributions :)

**Comment by gamersalpha** [comment]
wtf that 's means ?

**Comment by lapineige** [comment]
It means that there is no Mattermost version for Raspeberry Pi or any other computer based on the ARM architecture, ready to be used by Yunohost packagers.
So there is 2 options:
- building ("creating") a dedicated version directly before installing it, on the Raspberry Pi. This is not possible because it doesn't have enough memory for doing that.
- someone setup it's computer to build this specific version, and send it to the others. This require quite some work and need to be done again with each new version (and they are frequent…).
So @kemenaran is not going to do it - but if some generous person want to do it, it's fine :)

**Comment by gamersalpha** [comment]
i found this : 

https://developers.mattermost.com/contribute/server/developer-setup/

**Comment by SmartHoneybee** [comment]
Hi there,

cross-compiling an arm version on amd64 isn't that hard: https://github.com/SmartHoneybee/ubiquitous-memory
It's neither official nor a Yunohost package, but maybe you can use it to build what you need.

Have fun.

Regards,
Bee

**Comment by arthurlutz** [comment]
A forum post about this problem https://forum.yunohost.org/t/probleme-dinstallation-de-mattermost-the-user-was-not-dfound/6573/2

**Comment by gamersalpha** [comment]
Hello up to this, 

this apps reallymissing on my raspberry yunohost server

**Comment by kemenaran** [comment]
It seems Mattermost on a Raspberry could work. The only missing part is a buildbot that can reliably cross-compile the lastest version of Mattermost for ARM.

If someone can find or setup an ARM buildbot, I'm willing to do the work to include the arm version into the Yunohost script.

**Comment by kemenaran** [comment]
Turns out there is an ARM buildbot available here: https://github.com/SmartHoneybee/ubiquitous-memory/releases/

I guess the only missing step now would be to create an alternative `app.src` file, that can be updated with the latest Mattermost ARM build, and selected at runtime when running on ARM.

**Comment by harpogit** [comment]
I'm interested in Mattermost porting to ARM, but I don't have any skills to do it.
:-(
I wish I could help !

**Comment by dsmrs** [comment]
> Turns out there is an ARM buildbot available here: https://github.com/SmartHoneybee/ubiquitous-memory/releases/
> 
> I guess the only missing step now would be to create an alternative `app.src` file, that can be updated with the latest Mattermost ARM build, and selected at runtime when running on ARM.

Is there a step by step tutorial ?

**Comment by kemenaran** [comment]
ARM and ARM-64 versions are now packaged, so this should work on a Raspberry Pi.
